### ISSUE TITLE
量化后的模型size

### ISSUE THREAD

**Issue by liman13552763129** [FLHonker/ZAQ-code#2]
你好，非常感谢你开源你的工程！我对这篇文章很高兴，我使用你的代码尝试复现论文中的结果，在cifar10上使用train.py 训练resnet20(model size 1.1M)达到最优，然后使用main.py 量化模型，但是模型经过量化后模型size 仍为之前的1.1M,量化使用的参数--param_bits 5--bn_bits 5 --fwd_bits 5 ，尝试了不同量化参数和量化方式（linear|minmax|log|tanh|scale）均是如此，main.py执行万保存的ZAQ-cifar10-resnet20-5bit.pt即为量化后的模型吧？请问什么原因呢？很感谢的回复！

**Comment by FLHonker** [comment]
了解一下fake quantization，伪量化
