### ISSUE TITLE
The loss function is not consistent with Paper's claim.

### ISSUE THREAD

**Issue by viperit** [FLHonker/ZAQ-code#5]
Dear author,
I have found the loss function in your code is inconsistent with Paper's claim.
In the paper, you use Channel Relation Map (CRM) as the loss function which should only contain **channel_wise** L1 loss. 
But in the code, you use **SCRM** which contains **spatial_wise** and  **channel_wise** L1 losses. As shown as:
![image](https://user-images.githubusercontent.com/28667932/120457472-0f737600-c3c9-11eb-8120-8d998de82aab.png)

**Comment by FLHonker** [comment]
This is an improved version.
