### ISSUE TITLE
The channel_wise loss function may be incorrect.

### ISSUE THREAD

**Issue by viperit** [FLHonker/ZAQ-code#6]
Dear author,
**channel_wise** function of SCRM may be incorrect.

1. There is no **EMA**  and **exp** over layers as the paper's claim.
In code:
![image](https://user-images.githubusercontent.com/28667932/120458679-0d5de700-c3ca-11eb-95c8-c0da6502dd03.png)
In paper:
![image](https://user-images.githubusercontent.com/28667932/120458815-2ff00000-c3ca-11eb-8468-1ada10adb14e.png)

2. I cannot figure out the relationship between the **channel_wise** function and **Channel Relation Map (CRM)** as the paper's claim. 
3. Neither can I find the computation of  **Channel Relation Map (CRM)** in your code nor I can figure out what the code computes.
![image](https://user-images.githubusercontent.com/28667932/120458977-53b34600-c3ca-11eb-8199-07e661f8e4cf.png)

**Comment by YiminXu1996** [comment]
Same question as Viperit :(

**Comment by FLHonker** [comment]
This is a follow-up version, not consistent with the one used in the paper. You'd better use this.
