### ISSUE TITLE
The quantization function is asymmetric instead of symmetric function.

### ISSUE THREAD

**Issue by viperit** [FLHonker/ZAQ-code#7]
Dear author,
In your paper, you said you use **symmetric** quantization function but you use the **asymmetric** quantization function in your code.
In paper:
![image](https://user-images.githubusercontent.com/28667932/120730694-a26cf700-c514-11eb-8b40-d7239279c67b.png)
In code:
![image](https://user-images.githubusercontent.com/28667932/120730729-b31d6d00-c514-11eb-96d4-0f8e48cb76cb.png)
![image](https://user-images.githubusercontent.com/28667932/120730750-bdd80200-c514-11eb-9fb6-a894330e7411.png)

**Comment by FLHonker** [comment]
It's just an example. Many quantization strategies can be employed, such as tanh/minmax.

**Comment by FLHonker** [comment]
Sorry. The code is for reference only, this is Not exactly the same as the old version in the paper，because we are still doing new improvements.

**Comment by YiminXu1996** [comment]
If the code is just for reference, please point it out in your readme, just like: "This code is temporarily unreliable and we will upload a solid version for future use". Or it makes others, besides me and Viperit, confused when trying to use or even read your code.

Thanks

**Comment by FLHonker** [comment]
> If the code is just for reference, please point it out in your readme, just like: "This code is temporarily unreliable and we will upload a solid version for future use". Or it makes others, besides me and Viperit, confused when trying to use or even read your code.
> 
> Thanks

Thanks, we'll republic more details about the code.
